import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/navbar";
import Sidebar from "../../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script src="https://kit.fontawesome.com/267bd23fe0.js" crossOrigin="anonymous"></script>
            </head>
            <body className={inter.className}>
                <Navbar></Navbar>
                <Sidebar></Sidebar>
                {children}
            </body>
        </html>
    );
}
